// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent to suggest GST categories for invoice items.
 *
 * - suggestGstCategory - A function that suggests the GST category.
 * - GstSuggestionInput - The input type for the suggestGstCategory function.
 * - GstSuggestionOutput - The return type for the suggestGstCategory function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GstSuggestionInputSchema = z.object({
  itemDescription: z
    .string()
    .describe('The description of the invoice item.'),
});
export type GstSuggestionInput = z.infer<typeof GstSuggestionInputSchema>;

const GstSuggestionOutputSchema = z.object({
  gstCategory: z
    .string()
    .describe('The suggested GST category for the item.'),
  confidence: z
    .number()
    .describe(
      'A confidence score between 0 and 1 indicating the accuracy of the suggestion.'
    ),
});
export type GstSuggestionOutput = z.infer<typeof GstSuggestionOutputSchema>;

export async function suggestGstCategory(
  input: GstSuggestionInput
): Promise<GstSuggestionOutput> {
  return suggestGstCategoryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'gstSuggestionPrompt',
  input: {schema: GstSuggestionInputSchema},
  output: {schema: GstSuggestionOutputSchema},
  prompt: `You are an AI assistant specialized in suggesting GST (Goods and Services Tax) categories for invoice items.

  Given the item description, provide the most appropriate GST category and a confidence score (0 to 1) for your suggestion.

  Item Description: {{{itemDescription}}}
  `,
});

const suggestGstCategoryFlow = ai.defineFlow(
  {
    name: 'suggestGstCategoryFlow',
    inputSchema: GstSuggestionInputSchema,
    outputSchema: GstSuggestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
