
"use client"; 

import PageHeader from "@/components/page-header";
import { InvoiceForm, type InvoiceFormValues } from "@/components/invoice-form";
import { useToast } from "@/hooks/use-toast";
import { useRouter } from "next/navigation"; 
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { saveInvoice } from "@/lib/firestore-actions";
import type { StoredInvoice } from '@/types/database';
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";

// Moved outside the component to prevent recreation on every render
const defaultNewInvoiceValues: Partial<InvoiceFormValues> = {
  invoiceDate: new Date(), 
  dueDate: null, 
  items: [{
    productId: "",
    description: "",
    quantity: 1,
    price: 0,
    gstCategory: "",
    applyIgst: true,
    applyCgst: false,
    applySgst: false,
    igstRate: 18,
    cgstRate: 9,
    sgstRate: 9
  }],
  customerId: "",
  customerName: "",
  customerEmail: "",
  customerAddress: "",
  customerPhone: "",
  invoiceNumber: "", // Will be generated in InvoiceForm
  notes: "",
  termsAndConditions: "Payment due within 30 days. All goods remain property of the seller until paid in full.",
  paymentStatus: "Unpaid",
  paymentMethod: "",
  shipmentDetails: {
    shipDate: null, trackingNumber: "", carrierName: "", consigneeName: "", consigneeAddress: "",
    consigneeGstin: "", consigneeStateCode: "", transportationMode: "", lrNo: "", vehicleNo: "",
    dateOfSupply: null, placeOfSupply: ""
  },
  type: 'Tax Invoice', // Default type
};


export default function CreateInvoicePage() {
  const { toast } = useToast();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [docType, setDocType] = useState<StoredInvoice['type']>('Tax Invoice');

  const createMutation = useMutation({
    mutationFn: (newInvoice: Omit<StoredInvoice, 'id' | 'createdAt' | 'updatedAt'>) => saveInvoice(newInvoice),
    onSuccess: (invoiceId) => {
      toast({
        title: "Document Created",
        description: `Your document has been successfully created and saved.`,
      });
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      router.push(`/invoices/${invoiceId}`);
    },
    onError: (error) => {
      console.error('Error saving document:', error);
      toast({
        title: "Error",
        description: "Failed to create document. Please try again.",
        variant: "destructive",
      });
    },
  });

  const handleSubmit = async (data: InvoiceFormValues & { amount: number }) => {
    // The ID is generated by firestore, so we omit it here.
    const { id, ...invoiceData } = data;
    const finalData = { ...invoiceData, type: docType };
    createMutation.mutate(finalData);
  };

  const handleCancel = () => {
    router.push("/invoices");
  };

  return (
    <div className="space-y-6">
      <PageHeader title="Create New Document" description="Select a document type and fill in the details." />
      
      <Card>
        <CardContent className="pt-6">
          <Label className="text-base font-semibold">Document Type</Label>
          <RadioGroup value={docType} onValueChange={(value) => setDocType(value as StoredInvoice['type'])} className="flex space-x-4 mt-2">
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="Tax Invoice" id="tax-invoice" />
              <Label htmlFor="tax-invoice">Tax Invoice</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="Proforma Invoice" id="proforma-invoice" />
              <Label htmlFor="proforma-invoice">Proforma Invoice</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="Quotation" id="quotation" />
              <Label htmlFor="quotation">Quotation</Label>
            </div>
          </RadioGroup>
        </CardContent>
      </Card>

      <InvoiceForm 
        onSubmit={handleSubmit} 
        defaultValues={{...defaultNewInvoiceValues, type: docType}}
        isLoading={createMutation.isPending}
        onCancel={handleCancel}
      />
    </div>
  );
}
