
"use client"; 

import PageHeader from "@/components/page-header";
import { InvoiceForm, type InvoiceFormValues } from "@/components/invoice-form";
import { useToast } from "@/hooks/use-toast";
import { useRouter } from "next/navigation"; 
import { useState } from "react";
import { StoredInvoice } from "@/lib/database";
import { saveInvoice } from "@/lib/database-wrapper";

export default function CreateInvoicePage() {
  const { toast } = useToast();
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (data: InvoiceFormValues) => {
    setIsLoading(true);
    
    try {
      const subtotal = data.items.reduce((acc, item) => acc + (item.quantity || 0) * (item.price || 0), 0);
      let totalTaxAmount = 0;
      data.items.forEach(item => {
        const itemAmount = (item.quantity || 0) * (item.price || 0);
        if (item.applyIgst) {
          totalTaxAmount += itemAmount * ((item.igstRate || 0) / 100);
        } else {
          totalTaxAmount += itemAmount * ((item.cgstRate || 0) / 100);
          totalTaxAmount += itemAmount * ((item.sgstRate || 0) / 100);
        }
      });
      const totalAmount = subtotal + totalTaxAmount;

      const newInvoice: StoredInvoice = {
        ...data,
        id: data.invoiceNumber, 
        status: data.paymentStatus || "Unpaid", 
        amount: totalAmount,
        shipmentDetails: data.shipmentDetails || { // Ensure shipmentDetails exists
            shipDate: null, trackingNumber: "", carrierName: "",
            consigneeName: "", consigneeAddress: "", consigneeGstin: "", consigneeStateCode: "",
            transportationMode: "", lrNo: "", vehicleNo: "", dateOfSupply: null, placeOfSupply: ""
        },
      };

      const success = await saveInvoice(newInvoice);
      
      if (success) {
        toast({
          title: "Invoice Created",
          description: `Invoice ${data.invoiceNumber} has been successfully created and saved.`,
        });
        router.push("/invoices");
      } else {
        throw new Error("Failed to save invoice to database");
      }
    } catch (error) {
      console.error('Error saving invoice:', error);
      toast({
        title: "Error",
        description: "Failed to create invoice. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCancel = () => {
    router.push("/invoices");
  };

  // Default values for new invoice, including new shipment fields
  const defaultNewInvoiceValues: Partial<InvoiceFormValues> = {
    invoiceDate: new Date(),
    dueDate: new Date(new Date().setDate(new Date().getDate() + 30)),
    items: [{
      productId: "",
      quantity: 1,
      price: 0,
      gstCategory: "",
      applyIgst: true,
      applyCgst: false,
      applySgst: false,
      igstRate: 18,
      cgstRate: 9,
      sgstRate: 9
    }],
    customerId: "",
    customerName: "",
    customerEmail: "",
    customerAddress: "",
    invoiceNumber: "", // Will be generated by InvoiceForm
    notes: "",
    termsAndConditions: "Payment due within 30 days. All goods remain property of the seller until paid in full.",
    paymentStatus: "Unpaid",
    paymentMethod: "",
    shipmentDetails: {
      shipDate: null,
      trackingNumber: "",
      carrierName: "",
      consigneeName: "",
      consigneeAddress: "",
      consigneeGstin: "",
      consigneeStateCode: "",
      transportationMode: "",
      lrNo: "",
      vehicleNo: "",
      dateOfSupply: null,
      placeOfSupply: ""
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader title="Create New Invoice" description="Fill in the details below to create a new invoice." />
      <InvoiceForm 
        onSubmit={handleSubmit} 
        defaultValues={defaultNewInvoiceValues}
        isLoading={isLoading}
        onCancel={handleCancel}
      />
    </div>
  );
}

    